//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDIAMASTER
    {
        public int MediaId { get; set; }
        public string ParentMedia { get; set; }
        public string MediaName { get; set; }
        public string MediaType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
