//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELE_ENQUIRY_INFO
    {
        public int LeadsId { get; set; }
        public string TEI_PHONENO { get; set; }
        public string TEI_ID { get; set; }
        public string TEI_CUSTOMER_FIRSTNAME { get; set; }
        public string TEI_CUSTOMER_LASTNAME { get; set; }
        public Nullable<System.DateTime> TEI_CALLBACK_DATE { get; set; }
        public string TEI_CALLBACK_TIME { get; set; }
        public string TEI_CALLER_REMARKS { get; set; }
        public string TEI_POSSIBILITY { get; set; }
        public string TEI_STAGE { get; set; }
        public string TEI_EXECUTIVE_CODE { get; set; }
        public string TEI_OPTION { get; set; }
        public Nullable<System.DateTime> TEI_CALL_DATE { get; set; }
        public string TEI_CALL_TIME { get; set; }
        public string TEI_ENQUIRYFOR { get; set; }
        public string TEI_REVIEWEDBY { get; set; }
        public Nullable<System.DateTime> TEI_ASSIGN_DATE { get; set; }
        public string TEI_ASSING_TIME { get; set; }
        public string TEI_ASSIGN_ID { get; set; }
        public string TEI_ENQUIRY_TYPE { get; set; }
        public Nullable<decimal> TEI_SNO { get; set; }
        public string TEI_CALLER_TYPE { get; set; }
        public string TEI_CALL_STATE { get; set; }
        public string TEI_CUSTOMER_COMMENTS { get; set; }
        public string TEI_CALL_LOGS { get; set; }
        public string SourceCd { get; set; }
        public string TEI_VENTUIRE { get; set; }
        public string ENQ_VENTURE { get; set; }
        public string ENQ_SOURCE { get; set; }
        public string OTHER_ENQ_SOURCE { get; set; }
        public string MEDIA_ENQ_SOURCE { get; set; }
        public string MEDIA_SUB_ENQ_SOURCE { get; set; }
        public Nullable<int> CampaignCode { get; set; }
        public string REF_VENTURE { get; set; }
        public Nullable<int> REF_CODE { get; set; }
        public string WALKIN_TYPE { get; set; }
        public Nullable<System.DateTime> TEI_PURCHASE_DATE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string SourceCategory { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<int> Purchase_BatchId { get; set; }
        public string FirstSourceOfEnquiry { get; set; }
        public string OTHER_STATUS { get; set; }
        public Nullable<int> CUSTLEAD_ID { get; set; }
        public Nullable<int> CUSTLEAD_CTRL { get; set; }
    }
}
