//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELE_DESIGNATION_MASTER
    {
        public int DesignationId { get; set; }
        public string Designation { get; set; }
        public string Prefix { get; set; }
        public bool Active { get; set; }
    }
}
