//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRM2022Entities : DbContext
    {
        public CRM2022Entities()
            : base("name=CRM2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TELE_CALLER_MASTER> TELE_CALLER_MASTER { get; set; }
        public virtual DbSet<MEDIA_ENQUIRY_INFO> MEDIA_ENQUIRY_INFO { get; set; }
    }
}
