//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDIA_ENQUIRY_INFO
    {
        public int MId { get; set; }
        public Nullable<int> MediaLeadId { get; set; }
        public string M_EnquiryType { get; set; }
        public string M_FirstName { get; set; }
        public string M_LastName { get; set; }
        public string ISD { get; set; }
        public string M_PhoneNo { get; set; }
        public string M_EMailId { get; set; }
        public Nullable<System.DateTime> M_DateTime { get; set; }
        public string Project { get; set; }
        public string Query { get; set; }
        public string InterestedIn { get; set; }
        public string CustomerIdentity { get; set; }
        public string PhoneVerificationStatus { get; set; }
        public string EmailVerificationStatus { get; set; }
        public string M_Source { get; set; }
        public string UserID { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string CustomerStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> MCustLeadId { get; set; }
        public Nullable<int> MCustCtrl { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public Nullable<bool> Flag { get; set; }
    }
}
