//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELE_CALLER_MASTER
    {
        public string TCM_ID { get; set; }
        public string TCM_NAME { get; set; }
        public string TCM_ADDRESS1 { get; set; }
        public string TCM_ADDRESS2 { get; set; }
        public string TCM_CITY { get; set; }
        public string TCM_PIN { get; set; }
        public string TCM_PHONE { get; set; }
        public string TCM_MOBILE { get; set; }
        public string TCM_EMAIL { get; set; }
        public string TCM_TYPE { get; set; }
        public byte[] PHOTO { get; set; }
        public string TCM_EMAIL2 { get; set; }
        public Nullable<int> TCM_DESIGNATION { get; set; }
        public Nullable<int> REPORT_DESIGNATION { get; set; }
        public string REPORT_ID { get; set; }
        public Nullable<int> TEAM_ID { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
